# Default C%20FROM GitLab CI Pipeline

stages:
  - secret

secret_detection:
  stage: secret
  tags:
    - docker
  script:
    - echo "Secret detection running"
  rules:
    - if: $CO_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  allow_trigger: true
